### ISSUE TITLE
Release new version on crates.io

### ISSUE THREAD

**Issue by KalitaAlexey** [nix-rust/nix#286] opened 2016-02-28 14:35 UTC
I would like to make PR to mio.

**Comment by kamalmarhubi** [comment] 2016-02-28 16:50
We should be making a release this week!

Closing as duplicate of #269.

**Closed by kamalmarhubi** 2016-02-28 16:50 UTC

**Comment by kamalmarhubi** [comment] 2016-03-03 02:03
@KalitaAlexey we now have a [0.5.0](https://crates.io/crates/nix/0.5.0)!
