### ISSUE TITLE
Use --check-cfg to validate cfg attributes during automated builds

### ISSUE THREAD

**Issue by rtzoeller** [nix-rust/nix#1734] opened 2022-06-06 23:30 UTC
Consider enabling some form of the --check-cfg flag during automated builds, to catch typos.

https://github.com/rust-lang/cargo/issues/10554

**Comment by SteveLauC** [comment] 2024-01-15 04:39
#2293 is a duplicate of this issue, but I am going to close this one as the new one has more information and is up-to-date with the current Nix status:)

**Closed by SteveLauC** 2024-01-15 04:39 UTC
