### ISSUE TITLE
The relationship between std and nix

### ISSUE THREAD

**Issue by Kixunil** [nix-rust/nix#671] opened 2017-07-11 19:11 UTC
I've been thinking that `nix` and `std` provide some similar functionality (files, sockets, ...) but they are implemented twice.

Shouldn't `std` be implemented using `nix`? Or vice-versa? Or perhaps they should have a common dependency?

Code de-duplication would bring many benefits IMHO.

**Comment by Susurrus** [comment] 2017-07-11 19:33
I don't think there's any *actual* overlap between these crates though many concepts are shared between them. Looking through `std::os::unix` I don't see anything that's also in `nix`. Additionally while I  don't expect that to change as `std` is much more geared towards cross-platform development, while `nix` is not, and as such the platform-specific constructs will likely not grow too much more.

But maybe I missed something, can you name a specific part of `std` and `nix` that overlap in some fashion? I assume there was something specific that triggered this issue.

**Comment by Kixunil** [comment] 2017-07-11 21:03
I believe that e.g. [FileDesc](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/fd.rs) could be shared and possibly other things.

The way I see it:

* `libc` - platform-dependent C "header"
* `nix` - safe Rust; platform-dependent
* `std` - multi-platform abstraction

So `std` should probably be implemented using `nix`.

**Comment by Susurrus** [comment] 2017-07-11 21:07
It could be shared, but it couldn't exist in `nix`. `std` is basically the bottom of the dependency chain, so you can't put other things below it. Now if we wanted to reuse `FileDesc` in `nix`, which we actually might want to do, that's a little different as we do depend on `std` within our lib.

**Comment by Kixunil** [comment] 2017-07-11 21:20
I wonder if there is a technical reason for `std` being unable to depend on other crates or it's just a political decision.

**Comment by Susurrus** [comment] 2017-07-11 21:32
It's both. Rust is tightly coupled with `std`, as in they support the same systems, have the same development process, and share the same stability guarantees, so having full control of that stack is important for development. I'm going to close this as not really relevant, but if you'd like to continue this discussion I suggest you post on [the internals forums](https://internals.rust-lang.org/) as the actual devs could give you much better commentary than I can.

**Closed by Susurrus** 2017-07-11 21:32 UTC

**Comment by posborne** [comment] 2017-07-11 22:09
Yep, I agree with your answers @Susurrus.  Just because `std` could, conceivably, use nix doesn't mean it should.  Recently, mio even used away from using nix and has its own libc bindings where required and I think the choice was reasonable to reduce the number of dependencies for a very core piece of software that is probably at a greater level of maturity now than nix.

As nix continues to mature we may change structure or processes to encourage large projects to use nix without fear (e.g. exposing several smaller crates which are less likely to have regressions due to changes in unrelated code to what some other lib may care about).  Those ideas would be something to toss around more in another thread.

**Comment by Kixunil** [comment] 2017-07-12 10:16
Thank you for responses!
