### ISSUE TITLE
Make utimensat wrapper optionally take timestamps

### ISSUE THREAD

**Issue by sargun** [nix-rust/nix#1845] opened 2022-10-12 02:59 UTC
Right now, you have to pass both *mtime* and *atime* to the utimensat syscall wrapper. Infact, this is not required, and you can skip one of them by setting it to the magic value UTIME_OMIT. We should allow this. I'm not sure if this is a "stable" API or not.

**Comment by SteveLauC** [comment] 2022-10-12 22:47
Yes, I also want this. See [#1834](https://github.com/nix-rust/nix/issues/1834)

**Comment by rtzoeller** [comment] 2022-10-13 01:24
Closing as duplicate of #1834.

**Closed by rtzoeller** 2022-10-13 01:24 UTC
