### ISSUE TITLE
PollFd::new requires too restrictive lifetime

### ISSUE THREAD

**Issue by MaxVerevkin** [nix-rust/nix#2118] opened 2023-08-29 13:42 UTC
I was trying to do

```rust
if let Some(cmd_fd) = state.status_cmd_fd() {
    fds.push(PollFd::new(&cmd_fd, PollFlags::POLLIN));
}
```

where `status_cmd_fd()` returns `Option<BorrowedFd<'_>>`. This code does not compile because the _reference_ `&cmd_fd` does not live long enough, but the lifetime of the reference should be irrelevant.

---

Current signature of `PollFd::new`  is

```rust
pub fn new<Fd: AsFd>(fd: &'fd Fd, events: PollFlags) -> PollFd<'fd>
```

I think it should probably be

```rust
pub fn new<Fd: AsFd + 'fd>(fd: Fd, events: PollFlags) -> PollFd<'fd>
```

**Comment by asomers** [comment] 2023-09-23 15:27
Duplicate of #2130

**Closed** 2023-10-01 11:51 UTC
